### ISSUE TITLE
two files named `I/input.C` in src

### ISSUE THREAD

**Issue by jbae11** [svalinn/ALARA#38]
I get the following message when doing git clone:
```
Resolving deltas: 100% (3745/3745), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'src/Input.C'
  'src/input.C'

```

Might not be too big of a deal cause its easily fixable on the user end

**Comment by gonuke** [comment]
This was the consequence of a change to simplify the directory structure.  I'll make a quick change to rectify this.
