### ISSUE TITLE
Create a count of emitted particles for each reaction type

### ISSUE THREAD

**Issue by gonuke** [svalinn/ALARA#44]
Using the string description of emitted particles, process it to determine how many of each particle type are emitted.

**Comment by gonuke** [comment]
Store this information in a dictionary of form `{particle : number}`

**Comment by MicahGale** [comment]
I'm wondering if the GNDS data format has this information in an easy to interpret way. This might also be helpful for #43.

**Comment by gonuke** [comment]
Include a test that shows that this works for a few different cases
