### ISSUE TITLE
Calculate the change in nucleons for a given reaction

### ISSUE THREAD

**Issue by gonuke** [svalinn/ALARA#45]
Given the number of emitted particles of each type, determine what the change in nucleons is for a given reaction and store this information.  Include isomeric changes.  Store the result as an integer in the form of the KZA encoding.

**Comment by MicahGale** [comment]
Is the resulting isotope data including in the ENDF? I know file 6 has the nitty gritty, which is sometimes missing, but I wonder if file 3 has enough high level info to run with.

**Comment by gonuke** [comment]
Include a test that shows this works for a few representative cases
