### ISSUE TITLE
Determine list of reaction types in a given file

### ISSUE THREAD

**Issue by gonuke** [svalinn/ALARA#46]
For a single ENDF file, representing a single nuclide, determine the list of reaction types that exist in file MF=3.

**Comment by gonuke** [comment]
This should be focused on raw ENDF files and not yet on GENDF files.

**Comment by MicahGale** [comment]
> This should be focused on raw ENDF files and not yet on GENDF files.

My first thought of how to do this should be generalized to ENDF and GENDF, and would just be reading the MT numbers in the far right column.
